version: "3.3"
services:
    web:
        image: nginx:alpine
        container_name: lodel_server
        ports:
            - "9009:80"
            - "9010:443"
        links:
            - php
            - "db:database"
        networks:
            lodelnet:
                ipv4_address: 172.30.0.10
        volumes:
            - .:/code
            - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    
    php:
        build:
            context: .docker/fpm
            dockerfile: dockerfile
        container_name: lodel_php
        environment:
            - LOCAL_USER_ID=1000
        expose:
            - "9000"
        networks:
            lodelnet:
                ipv4_address: 172.30.0.20
        volumes:
            - .:/code
            
    db:
        image: wangxian/alpine-mysql
        ports:
            - "3306"
        container_name: lodel_db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: database
        networks:
            lodelnet:
                ipv4_address: 172.30.0.30
        volumes:
            - ./data/mysql/:/docker-entrypoint-initdb.d
            - ./data_volume:/var/lib/mysql

networks:
    lodelnet:
        driver: bridge