FROM php:5.6-fpm-alpine

RUN curl -o /usr/local/bin/gosu -sSL "https://github.com/tianon/gosu/releases/download/1.2/gosu-amd64" && \
    chmod +x /usr/local/bin/gosu && \
    apk del curl && \
    rm -rf /var/cache/apk/*

RUN docker-php-ext-install mysql
RUN docker-php-ext-install mysqli

RUN sed -i '/phpize/i \
	[[ ! -f "config.m4" && -f "config0.m4" ]] && mv config0.m4 config.m4' \
	/usr/local/bin/docker-php-ext-configure

RUN mkdir /code 

RUN sed -i "s|;*listen.owner\s*=\s*.*|listen.owner = user|g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s|;*listen.group\s*=\s*.*|listen.group = user|g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s|;*listen.mode\s*=\s*.*|listen.mode = 0660|g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s|user\s=\s.*|user = user|g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s|group\s*=\s*.*|group = user|g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s|;log_level\s*=\s*notice|log_level = notice|g" /usr/local/etc/php-fpm.d/www.conf

COPY .docker/fpm/entrypoint.sh /

# CMD
ENTRYPOINT ["/entrypoint.sh"]

CMD ["php-fpm"]
